from .genre_playlist_interface import GenrePlaylistView
from .sketeton_animation import GenrePlaylistsSkeleton
from .interface import GenrePlaylistsInterface
from .genres_interface import AllGenreInterface